

export const GET_COUNTRIES='GET_COUNTRIES'
export const GET_COUNTRY_BY_NAME='GET_COUNTRY_BY_NAME'
export const GET_ACTIVITIES='GET_ACTIVITIES'
export const FILTER_BY_CONTINENT='FILTER_BY_CONTINENT'
export const FILTER_BY_ACTIVITY='FILTER_BY_ACTIVITY'
export const ORDER='ORDER'