

export const GET_COUNTRIES='GET_COUNTRIES'
export const GET_COUNTRY_BY_NAME='GET_COUNTRY_BY_NAME'
export const GET_ACTIVITIES='GET_ACTIVITIES'
export const FILTER_BY_CONTINENT='FILTER_BY_CONTINENT'
export const FILTER_BY_ACTIVITY='FILTER_BY_ACTIVITY'
export const ORDER='ORDER'
export const POST_ACTIVITY='POST_ACTIVITY'
export const NEW_ACTIVITY='NEW_ACTIVITY'
export const GET_COUNTRIES_BY_ID='GET_COUNTRIES_BY_ID'
export const ORDER_BY_POPULATION='FILTER_BY_POPULATION'
export const ORDER_BY_AREA='ORDER_BY_AREA'